version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php8-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  nginx:
    image: nginx:1.20-alpine
    container_name: php8-nginx
    restart: always
    ports:
      - 83:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_app'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'usu_app'
      # You can use whatever password you like
      MYSQL_PASSWORD: '4Y2A4JC&p0l8'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '4Y2A4JC&p0l8'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: